# Generated by Django 4.2.4 on 2023-08-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_worker_password'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='NewsCategory',
            new_name='PostCategory',
        ),
    ]
