# Generated by Django 4.2.4 on 2023-08-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_news_post_rename_newscategory_postcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_ips', to='news.post')),
            ],
            options={
                'unique_together': {('post', 'ip_address')},
            },
        ),
    ]
