# Generated by Django 4.2.4 on 2023-08-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_viewedip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
