# Generated by Django 4.2.4 on 2023-08-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firts_name', models.CharField(max_length=30, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=30, verbose_name='Familya')),
                ('phone', models.CharField(help_text='Ushbu raqam         Hodimning tizimga kirishdagi username sifatidaham foydalaniladi', max_length=17, unique=True, verbose_name='Telefon raqam')),
                ('password', models.CharField(default='BeTmBWKU', editable=False, help_text='Ushbu parol         Xodimning tizimga kirishida ishlatiladi', max_length=10, verbose_name='Parol')),
                ('address', models.CharField(help_text="Masalan: Fayziobod qishlog'i Bog'ibo'ston                                ko'chasi 40-uy", max_length=100, verbose_name='Manzil')),
                ('image', models.ImageField(blank=True, upload_to='workers/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, editable=False, verbose_name='Qisqacha izoh')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['-created_at', 'is_active'],
            },
        ),
    ]
