# Generated by Django 4.2.4 on 2023-08-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='firts_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.CharField(default='59QkjtXQ', editable=False, help_text='Ushbu parol         Xodimning tizimga kirishida ishlatiladi', max_length=10, verbose_name='Parol'),
        ),
    ]
