# Generated by Django 4.2.4 on 2023-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_firts_name_worker_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='description',
            field=models.TextField(blank=True, verbose_name='Qisqacha izoh'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.CharField(default='xdWQx7Qz', help_text='Ushbu parol         Xodimning tizimga kirishida ishlatiladi', max_length=10, verbose_name='Parol'),
        ),
    ]
