# Generated by Django 4.2.4 on 2023-08-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_worker_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.CharField(default='he9RGgyV', help_text='Ushbu parol         Xodimning tizimga kirishida ishlatiladi', max_length=10, verbose_name='Parol'),
        ),
    ]
