# Generated by Django 4.2.4 on 2023-08-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_worker_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['-created_at', 'is_active'], 'permissions': [('add_post', 'Can add post'), ('add_postcategory', 'Can add post category'), ('change_post', 'Can edit post'), ('change_postcategory', 'Can edit post category'), ('view_post', 'Can view post'), ('view_postcategory', 'Can view post category'), ('delete_post', 'Can delete post'), ('delete_postcategory', 'Can delete post category'), ('view_appeal', 'Can view appeal')], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.CharField(default='FDCEI37Q', help_text='Ushbu parol         Xodimning tizimga kirishida ishlatiladi', max_length=10, verbose_name='Parol'),
        ),
    ]
