# Generated by Django 4.2.4 on 2023-08-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_worker_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['-created_at', 'is_active'], 'permissions': [('can_add_post', 'Can add post'), ('can_add_postcategory', 'Can add post category'), ('can_change_post', 'Can edit post'), ('can_change_postcategory', 'Can edit post category'), ('can_view_post', 'Can view post'), ('can_view_postcategory', 'Can view post category'), ('can_delete_post', 'Can delete post'), ('can_delete_postcategory', 'Can delete post category'), ('can_view_appeal', 'Can view appeal')], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.CharField(default='cqcafqjj', help_text='Ushbu parol         Xodimning tizimga kirishida ishlatiladi', max_length=10, verbose_name='Parol'),
        ),
    ]
