# Generated by Django 4.2.4 on 2023-08-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=30, verbose_name='Familya')),
                ('phone', models.CharField(max_length=17, verbose_name='Telefon')),
                ('address', models.CharField(max_length=100, verbose_name='Manzil')),
                ('content', models.TextField(help_text='Murojat shu yerga yozilgan', verbose_name='Murojat')),
                ('is_active', models.BooleanField(default=False, verbose_name="Murojatchi bilan bog'lanildi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Murojat vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
            options={
                'verbose_name': 'Aholi Murojati',
                'verbose_name_plural': 'Aholi murojatlari',
                'ordering': ['is_active', '-created_at'],
            },
        ),
    ]
